### PR TITLE
PrimeRepr improvements

### PR DESCRIPTION
**Pull request by ebfull**
These are API-breaking changes that make `PrimeRepr` a little nicer.

### CODE REVIEW

**Comment by str4d** [comment]
LGTM, though I can't attest to `add_nocarry` and `sub_noborrow` not needing to return anything.

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 541fda7 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 541fda758008330cc5c0093f9f7a8edb029e3eb9 with merge da717f447242289331dbada422811a5583615dc7...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/48), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/53), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/48), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/48)
Approved by: ebfull
Pushing da717f447242289331dbada422811a5583615dc7 to master...

**Pull request merged**
