### PR TITLE
Move benchmarks under benches/ so tests compile on stable

### LINKED ISSUE #36: Allow tests to be run on stable compiler
Right now the benchmarks use unstable compiler APIs, so we need to disable them for the stable compiler.

### PR DESCRIPTION
**Pull request by str4d**
Closes #36.

### CODE REVIEW

**Comment by str4d** [comment]
An upside to this approach is that the benchmarks are no longer executed with `cargo test`, which appears to speed it up. All tests and benchmarks are evaluated with `cargo bench` (with tests being ignored) as before.

**Comment by bmerge** [comment]
:umbrella: The latest upstream changes (presumably #41) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by ebfull** [comment]
Once rebased, I'm ACK on this.

I however need to change the CI to invoke `cargo bench` so we have coverage of benchmarks.

**Comment by str4d** [comment]
Rebased.

Note that the test command also need to be modified when running on stable:

```
cargo test --no-default-features
```

**Comment by ebfull** [comment]
Here's the old benchmarks running:

```
test bls12_381::bench_pairing_final_exponentiation ... bench:   1,678,086 ns/iter (+/- 55,553)
test bls12_381::bench_pairing_full                 ... bench:   2,531,865 ns/iter (+/- 205,006)
test bls12_381::bench_pairing_g1_preparation       ... bench:      12,754 ns/iter (+/- 224)
test bls12_381::bench_pairing_g2_preparation       ... bench:     222,608 ns/iter (+/- 4,031)
test bls12_381::bench_pairing_miller_loop          ... bench:     604,264 ns/iter (+/- 26,389)
test bls12_381::ec::g1::bench_g1_add_assign        ... bench:       1,232 ns/iter (+/- 29)
test bls12_381::ec::g1::bench_g1_add_assign_mixed  ... bench:         928 ns/iter (+/- 22)
test bls12_381::ec::g1::bench_g1_mul_assign        ... bench:     305,696 ns/iter (+/- 8,835)
test bls12_381::ec::g2::bench_g2_add_assign        ... bench:       4,101 ns/iter (+/- 85)
test bls12_381::ec::g2::bench_g2_add_assign_mixed  ... bench:       2,919 ns/iter (+/- 109)
test bls12_381::ec::g2::bench_g2_mul_assign        ... bench:     973,226 ns/iter (+/- 20,971)
test bls12_381::fq12::bench_fq12_add_assign        ... bench:         170 ns/iter (+/- 3)
test bls12_381::fq12::bench_fq12_inverse           ... bench:      23,215 ns/iter (+/- 776)
test bls12_381::fq12::bench_fq12_mul_assign        ... bench:       6,326 ns/iter (+/- 157)
test bls12_381::fq12::bench_fq12_squaring          ... bench:       4,419 ns/iter (+/- 64)
test bls12_381::fq12::bench_fq12_sub_assign        ... bench:         176 ns/iter (+/- 3)
test bls12_381::fq2::bench_fq2_add_assign          ... bench:          22 ns/iter (+/- 0)
test bls12_381::fq2::bench_fq2_inverse             ... bench:      12,773 ns/iter (+/- 469)
test bls12_381::fq2::bench_fq2_mul_assign          ... bench:         251 ns/iter (+/- 6)
test bls12_381::fq2::bench_fq2_sqrt                ... bench:     202,849 ns/iter (+/- 20,388)
test bls12_381::fq2::bench_fq2_squaring            ... bench:         203 ns/iter (+/- 33)
test bls12_381::fq2::bench_fq2_sub_assign          ... bench:          27 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_add_assign            ... bench:          16 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_from_repr             ... bench:          71 ns/iter (+/- 5)
test bls12_381::fq::bench_fq_into_repr             ... bench:          41 ns/iter (+/- 3)
test bls12_381::fq::bench_fq_inverse               ... bench:      12,499 ns/iter (+/- 210)
test bls12_381::fq::bench_fq_mul_assign            ... bench:          72 ns/iter (+/- 5)
test bls12_381::fq::bench_fq_negate                ... bench:          14 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_repr_add_nocarry      ... bench:           7 ns/iter (+/- 2)
test bls12_381::fq::bench_fq_repr_div2             ... bench:           5 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_repr_mul2             ... bench:           6 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_repr_num_bits         ... bench:           4 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_repr_sub_noborrow     ... bench:           7 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_sqrt                  ... bench:      36,588 ns/iter (+/- 746)
test bls12_381::fq::bench_fq_square                ... bench:          62 ns/iter (+/- 8)
test bls12_381::fq::bench_fq_sub_assign            ... bench:          18 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_add_assign            ... bench:          11 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_from_repr             ... bench:          38 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_into_repr             ... bench:          25 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_inverse               ... bench:       7,415 ns/iter (+/- 175)
test bls12_381::fr::bench_fr_mul_assign            ... bench:          38 ns/iter (+/- 6)
test bls12_381::fr::bench_fr_negate                ... bench:          12 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_repr_add_nocarry      ... bench:           6 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_repr_div2             ... bench:           5 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_repr_mul2             ... bench:           5 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_repr_num_bits         ... bench:           4 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_repr_sub_noborrow     ... bench:           6 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_sqrt                  ... bench:      42,955 ns/iter (+/- 4,768)
test bls12_381::fr::bench_fr_square                ... bench:          35 ns/iter (+/- 12)
test bls12_381::fr::bench_fr_sub_assign            ... bench:          10 ns/iter (+/- 0)
```

and the new benchmarks

```
test bls12_381::bench_pairing_final_exponentiation ... bench:   1,665,844 ns/iter (+/- 54,191)
test bls12_381::bench_pairing_full                 ... bench:   2,525,464 ns/iter (+/- 147,349)
test bls12_381::bench_pairing_g1_preparation       ... bench:      12,787 ns/iter (+/- 232)
test bls12_381::bench_pairing_g2_preparation       ... bench:     224,491 ns/iter (+/- 5,122)
test bls12_381::bench_pairing_miller_loop          ... bench:     610,639 ns/iter (+/- 20,249)
test bls12_381::ec::g1::bench_g1_add_assign        ... bench:       1,234 ns/iter (+/- 24)
test bls12_381::ec::g1::bench_g1_add_assign_mixed  ... bench:         928 ns/iter (+/- 22)
test bls12_381::ec::g1::bench_g1_mul_assign        ... bench:     306,265 ns/iter (+/- 22,990)
test bls12_381::ec::g2::bench_g2_add_assign        ... bench:       4,121 ns/iter (+/- 73)
test bls12_381::ec::g2::bench_g2_add_assign_mixed  ... bench:       2,917 ns/iter (+/- 212)
test bls12_381::ec::g2::bench_g2_mul_assign        ... bench:     997,570 ns/iter (+/- 19,537)
test bls12_381::fq12::bench_fq12_add_assign        ... bench:         182 ns/iter (+/- 2)
test bls12_381::fq12::bench_fq12_inverse           ... bench:      23,290 ns/iter (+/- 474)
test bls12_381::fq12::bench_fq12_mul_assign        ... bench:       6,336 ns/iter (+/- 113)
test bls12_381::fq12::bench_fq12_squaring          ... bench:       4,393 ns/iter (+/- 70)
test bls12_381::fq12::bench_fq12_sub_assign        ... bench:         171 ns/iter (+/- 2)
test bls12_381::fq2::bench_fq2_add_assign          ... bench:          32 ns/iter (+/- 0)
test bls12_381::fq2::bench_fq2_inverse             ... bench:      12,856 ns/iter (+/- 197)
test bls12_381::fq2::bench_fq2_mul_assign          ... bench:         265 ns/iter (+/- 16)
test bls12_381::fq2::bench_fq2_sqrt                ... bench:     202,266 ns/iter (+/- 6,949)
test bls12_381::fq2::bench_fq2_squaring            ... bench:         208 ns/iter (+/- 17)
test bls12_381::fq2::bench_fq2_sub_assign          ... bench:          30 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_add_assign            ... bench:          16 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_from_repr             ... bench:          75 ns/iter (+/- 4)
test bls12_381::fq::bench_fq_into_repr             ... bench:          41 ns/iter (+/- 19)
test bls12_381::fq::bench_fq_inverse               ... bench:      12,440 ns/iter (+/- 148)
test bls12_381::fq::bench_fq_mul_assign            ... bench:          66 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_negate                ... bench:          12 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_repr_add_nocarry      ... bench:           7 ns/iter (+/- 2)
test bls12_381::fq::bench_fq_repr_div2             ... bench:           5 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_repr_mul2             ... bench:           6 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_repr_num_bits         ... bench:           4 ns/iter (+/- 0)
test bls12_381::fq::bench_fq_repr_sub_noborrow     ... bench:           7 ns/iter (+/- 1)
test bls12_381::fq::bench_fq_sqrt                  ... bench:      36,860 ns/iter (+/- 2,079)
test bls12_381::fq::bench_fq_square                ... bench:          62 ns/iter (+/- 2)
test bls12_381::fq::bench_fq_sub_assign            ... bench:          13 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_add_assign            ... bench:          12 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_from_repr             ... bench:          41 ns/iter (+/- 2)
test bls12_381::fr::bench_fr_into_repr             ... bench:          25 ns/iter (+/- 1)
test bls12_381::fr::bench_fr_inverse               ... bench:       7,142 ns/iter (+/- 1,578)
test bls12_381::fr::bench_fr_mul_assign            ... bench:          35 ns/iter (+/- 1)
test bls12_381::fr::bench_fr_negate                ... bench:          10 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_repr_add_nocarry      ... bench:           6 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_repr_div2             ... bench:           5 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_repr_mul2             ... bench:           5 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_repr_num_bits         ... bench:           4 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_repr_sub_noborrow     ... bench:           6 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_sqrt                  ... bench:      42,223 ns/iter (+/- 657)
test bls12_381::fr::bench_fr_square                ... bench:          35 ns/iter (+/- 0)
test bls12_381::fr::bench_fr_sub_assign            ... bench:          10 ns/iter (+/- 0)
```

Props for keeping all the paths the same.

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 3ef34b7 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 3ef34b750c0003dfae8fde0765d9b64cd279175a with merge 1398a32b3aad8248b0f384595588e6f52ec03f45...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/25), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/27), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/25), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/25)
Approved by: ebfull
Pushing 1398a32b3aad8248b0f384595588e6f52ec03f45 to master...

**Pull request merged**
