### PR TITLE
Release of 0.13.1

### PR DESCRIPTION
**Pull request by ebfull**
This release features the following changes:

* The `byteorder` version is now set to `1` as conventional.
* The `CurveAffine`/`CurveProjective` traits now enforce that the scalar field of the `Engine` is the same scalar field for the curves.
* `Engine` is now `'static` and `Clone` to avoid problems with lifetime quirks and auto-derives.
* The scalar field of `Engine` is now guaranteed to be `SqrtField` which helps downstream abstractions.

In this PR I will be updating the `clippy` version and fixing any linting problems that show up. The builder should be using the newest nightly/stable versions of Rust also.

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit bb1ced0 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit bb1ced0bd7a1e73ce6123fbb1625d14f915069c0 with merge ed5a7f31e2a9c13626a1c14d504b47aa535a08a4...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/47)

**Comment by ebfull** [comment]
Updated builder to `nightly-2017-11-25`.

**Comment by ebfull** [comment]
@bmerge retry

**Comment by bmerge** [comment]
:zap: Previous build results for [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/44), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/44), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/44) are reusable. Rebuilding only [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/47)...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/44), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/48), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/44), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/44)
Approved by: ebfull
Pushing ed5a7f31e2a9c13626a1c14d504b47aa535a08a4 to master...

**Pull request merged**
