### PR TITLE
Use associated constants for simple constants like these.

### LINKED ISSUE #39: Use associated consts wherever possible
These have just been stabilized in Rust.

### PR DESCRIPTION
**Pull request by ebfull**
Closes #39.

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 4fe3e1d has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 4fe3e1d6e3d91c035687c931eb9254ade405d3f7 with merge 3e1562445ae6dfbadf3a2e52ffed4285b3f36f43...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/30), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/33), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/30), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/30)
Approved by: ebfull
Pushing 3e1562445ae6dfbadf3a2e52ffed4285b3f36f43 to master...

**Pull request merged**
