### PR TITLE
Update "rand" dependency to 0.4.

### PR DESCRIPTION
**Pull request by jasondavies**

### CODE REVIEW

**Comment by ebfull** [comment]
Note that `0.3` is in "compatibility mode" and so re-exports `0.4` interfaces, so we're already "using" `0.4`, except we're compiling 0.3 *as well*. The [changes](https://github.com/rust-lang-nursery/rand/blob/master/CHANGELOG.md) between 0.3 and 0.4 also do not affect our use of the APIs.

**Comment by daira** [comment]
We need to carefully review randomness quality, but this change doesn't cause any problem.

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 2338174 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 23381742446a9c97ef8d027d3dcbd7fec366ed92 with merge d51a5b0122fb732b0fc5afea605907f33203e9d5...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/49), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/54), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/49), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/49)
Approved by: ebfull
Pushing d51a5b0122fb732b0fc5afea605907f33203e9d5 to master...

**Pull request merged**
