### PR TITLE
Force public structures to implement Debug

### LINKED ISSUE #23: Force public structures to implement Debug
```rust
#![deny(missing_debug_implementations)]
```

### PR DESCRIPTION
**Pull request by str4d**
Closes #23.

### CODE REVIEW

**Comment by ebfull** [comment]
Thanks!

@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 3992018 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 39920186b337f05aac338acefc62607f8067cc7a with merge 9b6fb375331a8154b9a9122a4cb21b249897f950...

**Comment by str4d** [comment]
Still running?

**Comment by ebfull** [comment]
I had the wrong latent slave credentials set up for some reason.

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/24), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/26), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/24), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/24)
Approved by: ebfull
Pushing 9b6fb375331a8154b9a9122a4cb21b249897f950 to master...

**Pull request merged**
