### PR TITLE
G1/G2 rand() should produce elements of unknown exponent.

### LINKED ISSUE #60: Rand should produce points of unknown exponent
This is a stopgap for if we can't manage to get a solid G1/G2 hashing into this library before an audit begins. This allows us to build safe hashing on top, though it won't be as well-specified.

### PR DESCRIPTION
**Pull request by ebfull**
Closes #60.

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 12b9606 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 12b9606b9c6d73c4d116d5816967ad01906ffc67 with merge 30ae5d631318662acd3a7e6525075ec061393bad...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/37), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/40), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/37), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/37)
Approved by: ebfull
Pushing 30ae5d631318662acd3a7e6525075ec061393bad to master...

**Pull request merged**
