### PR TITLE
Implements and documents serialization

### LINKED ISSUE #11: Specify serialization
Currently a bit is set to distinguish between elements of compressed and uncompressed form, a bit is set to identify the "parity" of a compressed-form element. I should set another bit to indicate it's not the point at infinity, for the reason @daira suggests here: https://github.com/ebfull/pairing/commit/3faf8c526afc56ae9e2a995433c315e96fdfb80f#commitcomment-23094853

Looping in https://github.com/zcash/zcash/issues/2517 on this.

Once the serialization is changed (and fully tested against rejection test vectors #10) this ticket should be closed when it is specified in `src/bls12_381`.

### PR DESCRIPTION
**Pull request by ebfull**
Closes #11.

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge try

**Comment by bmerge** [comment]
:hourglass: Trying commit c618240c91aeb4ca950d947af90566a65e580ee7 with merge 3542d0033e2d0375218fb43e9c0a7233915fc97b...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-try](http://ci.bellman.rs:8010/builders/pairing-linux32-try/builds/0), [pairing-linux64-try](http://ci.bellman.rs:8010/builders/pairing-linux64-try/builds/0), [pairing-windows32msvc-try](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-try/builds/0), [pairing-windows64msvc-try](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-try/builds/0)
State: approved= try=True

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit c618240 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit c618240c91aeb4ca950d947af90566a65e580ee7 with merge 6df2c003c7a465a8b9553fcb6079d516c8f43241...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/0), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/0), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/0), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/0)
Approved by: ebfull
Pushing 6df2c003c7a465a8b9553fcb6079d516c8f43241 to master...

**Comment by daira** [comment]
Post-hoc ut(ACK+cov).

**Pull request merged**
