### PR TITLE
Bump version to 0.12.0.

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
Thanks go out to @mmaker and @str4d for contributing to this release. 🎉 

@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 0533941 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 05339414cc132555d3e4c93ba7d5ca18c3e94954 with merge 405553ee5a14892d4ecc9feb9c39643565eab21f...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/34)

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 67f5fbc has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 67f5fbc94c1ef45cb6c1ae3d428dccc4b2561399 with merge a8bf8362da1b8bdf8e0cea9fe96448fa9641855a...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/32), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/35), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/32), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/32)
Approved by: ebfull
Pushing a8bf8362da1b8bdf8e0cea9fe96448fa9641855a to master...

**Pull request merged**
