### PR TITLE
Version bump to 0.10.1

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit f111008 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit f111008d6634d5113ccfd340f7db098258194a01 with merge f9b7e53cf92a1b8810fbaf19b2952c5b566576d0...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/6)

**Comment by ebfull** [comment]
This is a bug with [clippy](https://github.com/rust-lang-nursery/rust-clippy), a code linter that is enabled during testing. I've filed https://github.com/rust-lang-nursery/rust-clippy/issues/1902.

**Comment by ebfull** [comment]
That bug is fixed and a new version of clippy was released.

@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 7960f69 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 7960f69ba9e110ae27296512c33afa2e00be20cc with merge aa5d634c044152bf32db8e22ca9db79239da1a6a...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/7), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/8), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/7), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/7)
Approved by: ebfull
Pushing aa5d634c044152bf32db8e22ca9db79239da1a6a to master...

**Pull request merged**
