### PR TITLE
Fix some comments

### PR DESCRIPTION
**Pull request by ebfull**
The `mod q` stuff was spotted by @Pratyush and/or @howardwu.

I just noticed the `// 2` typo.

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit b8394bf has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit b8394bf14dca69c2105cf7d34f1a76dd78db283e with merge cc8be5b7804e411b1d3139d33e27a755e73225a7...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/45), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/49), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/45), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/45)
Approved by: ebfull
Pushing cc8be5b7804e411b1d3139d33e27a755e73225a7 to master...

**Pull request merged**
