### PR TITLE
Simplify `pairing_benches`.

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit c38cb32 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit c38cb324f69440141cebd271a94179c46f679c5f with merge 68b57b2ce438cce03a99294195bac998225af608...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/27), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/29), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/27), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/27)
Approved by: ebfull
Pushing 68b57b2ce438cce03a99294195bac998225af608 to master...

**Pull request merged**
