### PR TITLE
s/is_in_correct_subgroup/is_in_correct_subgroup_assuming_on_curve/

### PR DESCRIPTION
**Pull request by mmaker**
I added a new method`is_in_correct_subgroup_assuming_on_curve` and added the method `is_in_correct_subgroup` for the `CurveAffine` trait.

### CODE REVIEW

**Comment by ebfull** [comment]
I don't want `is_in_correct_subgroup` to be a public API; if you have a `G1`/`G2`/`G1Affine`/`G2Affine` element the library guarantees it's in the correct subgroup already. :)

**Comment by ebfull** [comment]
So, this PR could just rename to `is_in_correct_subgroup_assuming_on_curve` but keep everything semantically the same. :)

**Comment by mmaker** [comment]
euh, done. sorry for wasting your time on this one.

**Comment by ebfull** [comment]
@mmaker You're not wasting anyone's time! That's what code review is for! :)

@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit ec49fcc has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit ec49fcc63801b663b46a7b57f342716e02dd80c4 with merge 68747b41746cead34ba94c754ffebbe345414a27...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/18), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/20), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/18), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/18)
Approved by: ebfull
Pushing 68747b41746cead34ba94c754ffebbe345414a27 to master...

**Pull request merged**
