### PR TITLE
Use 1 for the byteorder crate's version.

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 342b94c has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 342b94c76bf8257e14bcf94914a5eea33d5de4e5 with merge 5d9f77f5bf343907c3fc34b1b852379d399e0f27...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/40), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/43), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/40), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/40)
Approved by: ebfull
Pushing 5d9f77f5bf343907c3fc34b1b852379d399e0f27 to master...

**Pull request merged**
