### PR TITLE
Fix some minor typos in docs.

### PR DESCRIPTION
**Pull request by jasondavies**

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit d2f47cf has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit d2f47cfa2d3306f0367eb373cb04a70c85b0a38a with merge 3fbe45b1f5f4581d32bdf32b3a9347a2cc15f914...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/16)

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 122d2b1 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 122d2b161d380c23da15f4ee6fc6a648917a25b7 with merge 990401395cf1b137195f087342e445962bfe70e3...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/15), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/17), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/15), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/15)
Approved by: ebfull
Pushing 990401395cf1b137195f087342e445962bfe70e3 to master...

**Pull request merged**
