### PR TITLE
Random encoding/decoding tests for `PrimeFieldRepr`

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 176c77d has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 176c77d60297f36085be6201f8db5f9da3a1f6a5 with merge 8fc026bb6105620302e0401a7a37e1c3101d5ddb...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/3), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/3), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/3), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/3)
Approved by: ebfull
Pushing 8fc026bb6105620302e0401a7a37e1c3101d5ddb to master...

**Pull request merged**
