### PR TITLE
Replace inline value with const.

### PR DESCRIPTION
**Pull request by jasondavies**

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit b1d981e has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit b1d981e9165b779d2afe2519a452dcce87b6e70a with merge 2eb25d22984778273ca009a8936fb00ce9da2125...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/16), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/18), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/16), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/16)
Approved by: ebfull
Pushing 2eb25d22984778273ca009a8936fb00ce9da2125 to master...

**Pull request merged**
