### PR TITLE
Enable clippy linting

### LINKED ISSUE #5: Run everything against clippy
https://github.com/Manishearth/rust-clippy

### PR DESCRIPTION
**Pull request by ebfull**
Closes #5

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 451b2c3 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 451b2c30ad034d6bed397c786050bdbfb3b03a7e with merge 7c35f2b8b00eb2ba94e136d6e09ff4912ca18e2f...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/1), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/1), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/1), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/1)
Approved by: ebfull
Pushing 7c35f2b8b00eb2ba94e136d6e09ff4912ca18e2f to master...

**Pull request merged**
