### PR TITLE
Introduce a more typesafe wNAF API, and remove the unstable-wnaf feature

### LINKED ISSUE #27: Stable wNAF API
Currently you have to opt-in to it because it's a low level API. I want a simple API that you cannot misuse.

### PR DESCRIPTION
**Pull request by ebfull**
Closes #27.

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge try

**Comment by bmerge** [comment]
:hourglass: Trying commit d230603190174d3f9ac278faddf2de86b3fcfb3b with merge 81bc1047de8d76e7513dd4066d3090a2975d1968...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [pairing-linux64-try](http://ci.bellman.rs:8010/builders/pairing-linux64-try/builds/2)

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 06f6334 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 06f6334679fc09e4bad207955722decb2111757e with merge 5c814216d3306f133f87016a6c130974024b890f...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/28)

**Comment by ebfull** [comment]
Just lints.

This can sit here and accumulate some review while I see if the API satisfies all my use cases.

**Comment by ebfull** [comment]
@bmerge try

**Comment by bmerge** [comment]
:hourglass: Trying commit bda22db9d5907d64782f30fa4caebf5d511fddfa with merge ff95704eb40a95c62db54eb17a6bbf438566d09b...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [pairing-linux64-try](http://ci.bellman.rs:8010/builders/pairing-linux64-try/builds/3)

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 6708878 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 6708878f4cdebbd424d9dc2f3fc5506288cd8b53 with merge 2540ab30fbe530e53b9ceff2347d7926d4e9582e...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/28), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/30), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/28), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/28)
Approved by: ebfull
Pushing 2540ab30fbe530e53b9ceff2347d7926d4e9582e to master...

**Pull request merged**
