### PR TITLE
Add pairing_with API.

### LINKED ISSUE #8: pairing method on G1/G2
This makes it easier to work with the elements generically.

### PR DESCRIPTION
**Pull request by ebfull**
I needed this for something I'm doing so I just wrote it.

Closes #8

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 41834bc has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 41834bc4b235d0aae1261bee273b71394a4c9c46 with merge c643f0b1fa6def93a14351d5834fddd253195122...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/5), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/5), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/5), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/5)
Approved by: ebfull
Pushing c643f0b1fa6def93a14351d5834fddd253195122 to master...

**Pull request merged**
