### PR TITLE
Scalar field should be guaranteed to be SqrtField

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit aa0cc06 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit aa0cc06e5e6a06228d0e83c9ca45e1abe7c1614a with merge df9d2aaa373d6f19e990e0cb9a3c4a7be0ee93bb...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/43), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/46), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/43), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/43)
Approved by: ebfull
Pushing df9d2aaa373d6f19e990e0cb9a3c4a7be0ee93bb to master...

**Pull request merged**
