### PR TITLE
Release 0.11.

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
Thanks to @mmaker and @jasondavies for contributing to this release, as well as @daira and @zmanian for helpful code review and feedback.

@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 1239b76 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 1239b7648d11fdb30187632dba9ad32326d1511c with merge c4c6e25bc012ecaad60995beb69cce767ef09abc...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/20), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/22), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/20), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/20)
Approved by: ebfull
Pushing c4c6e25bc012ecaad60995beb69cce767ef09abc to master...

**Pull request merged**
