### PR TITLE
Bump version to 0.13.0

### PR DESCRIPTION
**Pull request by ebfull**
After #58 and #63 are merged.

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 39c25cd has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 39c25cd506268088cd6ad700901986273ec70daa with merge 48044a853f4b09ab9bd084306585bcae15cafac5...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/39), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/42), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/39), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/39)
Approved by: ebfull
Pushing 48044a853f4b09ab9bd084306585bcae15cafac5 to master...

**Pull request merged**
