### PR TITLE
Version bump.

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 59765c5 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 59765c5830fdb0c80b3fe1abcb1e3d8a685273d7 with merge f51a383ef15fb9393de280cb26b566fd0a2591b5...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/4), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/4), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/4), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/4)
Approved by: ebfull
Pushing f51a383ef15fb9393de280cb26b566fd0a2591b5 to master...

**Pull request merged**
