### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit dbac57c has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit dbac57c27bc4628abe0170d73ea5d2b67193bfff with merge dfb836170bfda4d3cbc8e0eb0ac2560c08dbd89a...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/34), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/37), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/34), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/34)
Approved by: ebfull
Pushing dfb836170bfda4d3cbc8e0eb0ac2560c08dbd89a to master...

**Pull request merged**
