### PR TITLE
Derive `Clone` for G1/G2 encodings.

### LINKED ISSUE #55: Re-enable expl_impl_clone_on_copy
This is a clippy lint that I'm disabling temporarily until the next Rust stable release which automatically implements clone for `[T; N]` (where T: Copy). The explicit `Clone` impls can be replaced with derives without affecting the API.

### PR DESCRIPTION
**Pull request by ebfull**
AFAIK this will finally work on stable when the next version of Rust is released.

Closes #55

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 6088752 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 60887521b6bd2dc18052b2bea750a7c825b62801 with merge 364796d88ccb007c332ac22889513612fff80a62...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/38), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/41), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/38), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/38)
Approved by: ebfull
Pushing 364796d88ccb007c332ac22889513612fff80a62 to master...

**Pull request merged**
