### PR TITLE
Engine should always be 'static, for flexibility in downstream code.

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
I also made it so that `Engine` must be `Clone`.

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 4a1ac94 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 4a1ac947995f9e38b783e0b987cdcb391ed4c9a8 with merge affead11a5852709ad9f00b98d0ac014c51c58e8...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/42), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/45), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/42), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/42)
Approved by: ebfull
Pushing affead11a5852709ad9f00b98d0ac014c51c58e8 to master...

**Pull request merged**
