### PR TITLE
Update clippy and fix code indentation.

### PR DESCRIPTION
**Pull request by jasondavies**
(The code indentation issue was not caught by clippy -- I noticed it by chance!)

### CODE REVIEW

**Comment by ebfull** [comment]
Thanks! This might not work because I may need to update the nightly on the CI. Also the CI might not even work...

@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit bce9f5d has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit bce9f5d639dc5d45435435674abbdb6dc1417d2f with merge 7b6e13bcb9a3683928878039907aee1004fdcf26...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/51)

**Comment by ebfull** [comment]
@bmerge retry

**Comment by bmerge** [comment]
:zap: Previous build results for [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/47), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/47), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/47) are reusable. Rebuilding only [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/51)...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/47), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/52), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/47), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/47)
Approved by: ebfull
Pushing 7b6e13bcb9a3683928878039907aee1004fdcf26 to master...

**Pull request merged**
