### PR TITLE
Even more adjustments

### LINKED ISSUE #22: Make Fq6 public

### LINKED ISSUE #24: PrimeField needs From<u64>
Requires the guarantee that all prime field moduli > 2^64...

### LINKED ISSUE #25: Define Engine associated type over Curve/CurveAffine

### PR DESCRIPTION
**Pull request by ebfull**
Closes #22
Closes #24
Closes #25

### CODE REVIEW

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 964fad5 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 964fad5a67ab9d149ded86bdb3283a72589cd93d with merge 22b3878997c9af89c2030a9e6c8717989af64c24...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/9)

**Comment by ebfull** [comment]
Clippy updated again.

@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit ba2c9c7 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit ba2c9c7bf0a19d359b845146c91485eea557d8f2 with merge 3babb820907e7ca2a145bee9afa6b6974467a139...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/10)

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 34aa52b has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 34aa52b0f7bef705917252ea63e5a13fa01af551 with merge caab085039555b0fa0b12a3b330cb32fe821fcb4...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/11)

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 6410bdf has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 6410bdf998d48a5b4f9753ad8030e83a655ae50c with merge cca6c971b83574bb455207827a0a5c601ff278e9...

**Comment by bmerge** [comment]
:boom: Test timed out

**Comment by ebfull** [comment]
@bermege r+

**Comment by bmerge** [comment]
:pushpin: Commit ca5efdc has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit ca5efdcebefb0f7ff2f0096c14e66cbd316ad8bc with merge 8d67be786cb365c10edcc84c9d8fb2938eac81df...

**Comment by bmerge** [comment]
:broken_heart: Test failed - [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/14)

**Comment by ebfull** [comment]
@bmerge r+

**Comment by bmerge** [comment]
:pushpin: Commit 766c902 has been approved by `ebfull`

**Comment by bmerge** [comment]
:hourglass: Testing commit 766c902d8c0650e7c72870aeb6168024added33c with merge d72929f64eb6eac266f437de2f4f74e26a6114b5...

**Comment by bmerge** [comment]
:sunny: Test successful - [pairing-linux32-auto](http://ci.bellman.rs:8010/builders/pairing-linux32-auto/builds/13), [pairing-linux64-auto](http://ci.bellman.rs:8010/builders/pairing-linux64-auto/builds/15), [pairing-windows32msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows32msvc-auto/builds/13), [pairing-windows64msvc-auto](http://ci.bellman.rs:8010/builders/pairing-windows64msvc-auto/builds/13)
Approved by: ebfull
Pushing d72929f64eb6eac266f437de2f4f74e26a6114b5 to master...

**Pull request merged**
